INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('SUMA', 5, 3, 8);

INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('RESTA_N', 10, 3, 7);

INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('MULTIPLICACION', 4, 2, 8);

INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('DIVISION', 8, 2, 4);

INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('POTENCIA', 3, 3, 27);

INSERT INTO OPERACION (TIPO, OPERANDO1, OPERANDO2, RESULTADO)
VALUES ('RAIZ_2', 4, 2, 2);

